#Rock   1
#Pop    2
#Electronica    3
#Hip hop    4
album_valor = [3.36,4.14 ,4.26,4.17,3.61,3.95,3.66,3.94,3.43,3.82,4.25,3.84,3.15,3.45,3.65,3.54,3.99,4.16,4.24,3.61,
               3.82,3.25,4.12,2.81,2.88,3.66,3.65,3.14,3.52,4.16,3.50,3.39,3.15,3.53,3.44,3.60,4.10,5,3.48,2.60,3.67,
               3.56,3.74,4.09,3.75,3.80,4.03,3.58,3.67,3.96,3.16,3.79,4.15,4.21,3.43,3.07,3.73,3.83,3.31,3.96,3.63,3.73,
               4.14,3.85,3.77,3.35,3.29,3.98,2.69,3.74,4.38,3.71,3.69,4.24,4.34,3.89,4.08]
album_nombre = ["hyperdrama","souvlaki","kid a","the glow pt2","vidrio","de todas las flores","isolation",
                "sound of silver","astroworld","syro","loveless","bright future","gamma",
                "The road to hell is paved with good intentions"," † (cross)",
                "the head hurts but the heart knows the truth","daughter of darkness","F♯A♯∞",
                "Lift Yr. Skinny Fists Like Antennas to Heaven!","Bonito Generation","Time 'n' Place",
                "jazz is for ordinary people","love deluxe","i'll be okay","Hurting","so tonight that i might see",
                "SAVED","with a hammer","motomami","heaven or las vegas","nuevos aires","orbweaving","discos revenge",
                "to hell with it","everything is alive","pure heroine","the money store","blonde","trench","blurryface",
                "desire, i want to turn into you","ugly","random access memories","discovery","r plus seven",
                "For the First Time","Ants From Up There","Top Ten most Epic fish of all time",
                "Me chama de gato que eu sou sua","Today I Laid Down","A Crow Looked at Me","Braemar","twin fantasy",
                "homogenic","long season","human after all","U D D","The Colours of Chloë","Apocalypse, Girl",
                "Mama's Gun","First Light","mint jams","All Screwed Up 2", "Ceres & Calypso in the Deep Time","lahai",
                "10,000 gecs","7s","post","her loss","Mr. Morale & The Big Steppers","To Pimp a Butterfly","die lit",
                "Nightlife E.P","The Dark Side of the Moon","Wish You Were Here","kids see ghosts","igor"]
album_genero = [3,1,1,1,1,2,2,1,4,3,1,1,3,3,3,3,1,1,1,2,2,3,2,1,1,2,1,2,2,2,2,1,3,2,1,2,4,4,1,2,2,4,3,3,3,1,1,3,2,1,1,3,1,3,1,3,3,2,2,2,4,2,2,4,1,4,3,1,2,4,4,4,4,1,1,1,4,4]
album_resena = ["El primer album de Justice en 7 años, regresa a sus raices con colaboraciones de artistas como Tame impala",
                "El clasico del shoegaze de slowdive es un album que define el genero y con sonidos etereos y letras de desamor",
                "Este album marca una reinvencion de la banda, usando sonidos mas electronicos, siendo un favorito personal, por su portada y sonidos extraños per familiares"
                "Eeste album de Phil Everlum, es una obra maestra del folk, siendo uno de los albumes con sonidos mas naturales que conozco"
                "Este album por Mabe Fratti y Hector Trosta, marca un paso hacia adelante para el movimiento de jazz avant gardista de la CDMX",
                "Este album es uno vulnerable, humano y natural, con letras y sonidos intimos, pintan un paisaje personal y pristino",
                "El debut de Kali Uchis usa un sonido interesante, mezclando pop con R&B, con colaboraciones que hacen bailar",
                "Este album de LCD Sounsystem perfecciona su clasico sonido de disco/rock progresivo, un clasico del rock disco",
                "Este album catapultó a la fama mundial a Travis Scott, con colaboraciones gigantes como Drake, Frank Ocean y mas",
                "El regreso de Aphex Twin es un album de IDM, con canciones fuera de este mundo y una de mis canciones favoritas de todos los tiempos, aisatsana[102]",
                "Este album es un clasico por muchos considerado la epitome del genero shoegaze, guitarras llenas de efectos y vocales indistinguibles son caracteristicas de este album ",
                "El ultimo album de Adrianne Lenker es un album casi completamente acustico, con vocales hermosas y temas comunes",
                "El regreso de Gessaffelstein es corto, pero lleno de energia y sonidos extraños",
                "El album del DJ vegyn esta lleno de sintetizadores ambientales etereos, y percusiones divertidas, con colaboraciones interesantes",
                "El debut de Justice es atrevido, agresivo y casi indescifrable, con sintetizadores abrasivos y composiciones felices, es un clasico del french touch",
                "Este album de Headache, es un album de poesia absurdista, declamado por una voz de IA, tiene momentos hermosos, tristes, divertidos y sorpresivamente humanos",
                "Este album de rock progresivo con tematica de terror te llena la cabeza de sonidos perturbadores que pintan perfectamente el nombre satanico de las canciones",
                "El album debut de la banda,Godspeed You! Black Emperor habla sobre el apocalipsis y de el ciclo vicioso del deseo y arrepentimiento humano, un poco dificl de escuchar dado a su duracion",
                "Un clasico del rock progresivo, que tiene sonidos increibles y cambio el panorama de la musica en su tiempo",
                "El segundo album de Kero Kero Bonito es una carta de amor a el pop con sonidos agresivamente optimistas y colores brillantes",
                "Este album marca un cambio de pagina en el sonido de Kero Kero Bonito, inclinandose un poco mas al rock o shoegaze, usando las vocales de sarah de manera increible",
                "El ep debut de el artista Berlioz, hace una fusion entre el jazz y el house",
                "El clasico del soul de Sade usa vocales hermosas y relajantes con instrumentales suaves",
                "Sign crushes motorist se posiciona como uno de los mayores exponentes del slowcore con este album y letras clasicas de adolescente deprimido",
                "El segundo album de sign crushes motorist, mejora y diversifica su sonido, manteniendo las letras y sonidos deprimentes",
                "Este album es un clasico del dreampop, con vocales hermosas e instrumentacion simple pero eterea",
                "El primer album bajo su nombre de nacimiento, Kristin Hayter muestra un album de terror sobre el sufrimiento, encontrado en la religion y el adoctrinamiento detras de esta",
                "El debut de Yaeji toma influencias de ambient, pop y mas, haciendo un buen album de electronica pop",
                "Este album marca una reinvencion de Rosalia y del genero, mostrando sonidos no convencionales en el panorama mainstream",
                "Este album es un clasico por su sonido etereo y vocales increibles ",
                "El segundo album de Girl Ultra nos muestra un R&B en español hermoso",
                "El album de midwife tiene vocales interesantes y melodias casi ambient y shoegaze",
                "El album de Neon Vectors nos muestra el porque mexico domina la escena del neon funk, con sonidos electronicos felices",
                "El debut de pinkpantheress nos muestra una expansion de su sonido clasico de pop",
                "El album de la banda slowdive nos muestra como es regresar a un genero años despues",
                "Lorde nos muestra un album intimamente adolescente, con letras con las que cualquier adolescente podra ismpatizar",
                "Death Grips nos muestra un salto hacia adelante en el genero del hip hop experimental, con musica y vocales violentas",
                "Blonde es mi album favorito de todos los tiempos, un album generacional y de los mas influyentes de la ultima decada",
                "El album de twenty one pilots nos muestra, instrumentales oscuras y percusiones interesantes",
                "El album que catapultó a twenty one pilots a la fama, lleno de hits y momentos interesantes",
                "El album de Caroline Polcachek nos muestra un momento interesante en el pop alternativo",
                "El album de slowthai se aventura en lo feo de la vida, adicciones, dolor y mas, con sonidos agresivos",
                "El ultimo album de Daft Punk, nos da musica pristina, que suena elegante y trabajada, con una de las mejores mezclas de la musica moderna",
                "El segundo album de Daft Punk, nos muestra musica creativa y divertida, marcando toda una generacion de creadores de musica"
                "Un album de ambient interesante, con musica interesante y extraña"
                "El debut de Black Country, New Road que empuja el genero del rock a una direccion llena de jazz e instrumentos no comunmente asociados con el genero",
                "El segundo album de Black Country, New Road, nos muestra una evolucion del grupo, con musica increible y letras de desamor y abandono",
                "El album de Ana Frango Eletrico, mezcla funk soul para lograr musica divertida",
                "Este album muestra una faceta interesante de los pensamientos de personas jovenes, con una historia detras del album desgarradora"
                "Un album completamente deprimente de Phil Everlum, escrito y grabado despues de la muerte de su esposa",
                "Un album de ambient con inspiraciones en animales, como gatos",
                "Un album de Car seat headrest sobre el desamor, y la manera de ver los sentimientos de una persona joven",
                "Un album con experimentaciones adelantadas a su epoca y un clasico del genero dado por Bjork",
                "Un album progresivo de Fishmans con momentos emocionantes e increiblemente interesantes",
                "Un album feliz y divertido con momentos de R&B",
                "Album instrumental con canciones largas y relajantes",
                "Un album extraño con vocales hermosas y momentos de ambient",
                "Erykha Badu nos regala un album increible de soul y R&B",
                "Un album de city pop y jazz, feliz y con musica divertida",
                "Album en vivo de la banda Casiopea, utilizando jazz para hacer musica divertida",
                "El album de DJ Screw que popularizo un movimiento del hip hop de llenar de efectos la musica",
                "Un album de shoegaze lleno de texturas, sonidos y efectos interesantes, que suena muy parecido a su portada",
                "El regreso a la musica de Sampha, con musica sobre crecer, vivir y sentimientos, R&B sobresaliente",
                "El segundo album de 100 gecs, donde se reinventan, usando ska, noise y mas",
                "Avey Tare nos regala un album progresivo con sonidos retumbantes y letras extrañas que hacen un album psicodelico",
                "Un album de Bjork que como siempre, reinventa su sonido y cambia el panorama de la musica de su epoca",
                "Despues de 5 años, Kendrick Lamar nos regala un album intimo donde habla de problemas personales como traumas, normalmente tabu en el hip hop"               
                "Considerado uno de los mejores albumes de la historia y el hip hop, este album aborda tantos temas que no se pueden discutir de manera corta, con musica interesante y letras aun mas",
                "Un album de Playboi Carti que cambia el panorama de el trap y como suena",
                "Yuragi hacen un EP de shoegaze interesante y un poco mas pesado de lo usual",
                "Un clasico de el rock progresivo, que suena psicodelico, lleno de reverberaciones y musica interesante que no parece ser eterna",
                "Otro clasico de el rock psicodelicp y progresivo, con canciones largas e interesantes, junto con letras introspectivas",
                "Un album colaborativo de Kanye West y Kid Cudi, que es el pico de su creatividad, usando rock, samples y hablando de temas personales de salud mental",
                "Una reinvencion completa de Tyler, the creator, con temas de desamor de manera agresiva, triste y feliz"] 